# Site settings
title: Baptiste Meurant
email: baptiste@meurant.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://baptiste.meurant.io" # the base hostname & protocol for your site
description: Software craftsman, full stack developer, architect, open source enthousiast
twitter_username: bmeurant
github_username:  bmeurant

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments
exclude: [package.json, bower.json, node_modules, bower_components, Gemfile, Gemfile.lock, less, Gruntfile.js]
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: true
